void createScreenWelcome(string s);
void CreateScreen();
void CreateNode(int x, int y, char name[], int color);
void CreatePhim(int x, int y, char name[]);
string AddName_Weight(string name);
bool CheckNode(int x, int y, int mx, int my);
bool CheckPos(Node *node[], int numberNode, int mx, int my);
bool AddNode(Node *node[], int numberNode, int &x, int &y, string &ten, bool flag);
void Rename(int x, int y, string &ten);
void NotificationFull(string Noti);
void SubEffectFile(int x1, int y1, int x2, int y2, char a[], int color);
void SubEffectToolbar(int x1, int y1, int x2, int y2, char a[], int color);
void SubEffectMenu(int x1, int y1, int x2, int y2, char a[], int color);
void EffectToolbar();
void EffectFile();
void EffectMenu();
void drawtriangle(int x1, int y1, int x2, int y2);
void drawcurved1(int x1, int y1, int x2, int y2, char *tt);
void Create_curved(int x1, int y1, int x2, int y2, char *tt);
void Create_line(int x1, int y1, int x2, int y2, char *tt);
